name: rest_client
description: REST API Client.
publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  http: ^1.1.0
  path: ^1.8.3

dev_dependencies:
  flutter_lints: ^2.0.0